<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{ab4dde46-4af9-4f37-baaf-4f46d01c1d2e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbMotor			:FB_M;
	fbValve			:FB_S;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbMotor();
fbValve	();	]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="8" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>